### ISSUE TITLE
Understanding chaining + extension: why don't valid paths in a GFA have end-to-end alignments?

### ISSUE THREAD

**Issue by rlorigro** [at-cg/PanAligner#1]
Hi,

Thanks for this new addition to the graph alignment ecosystem, it is very much appreciated. 

I am having issues with a simple test in which I take a 3 node GFA and then concatenate a path and align the resulting sequence back to the GFA to see if it is found again.

Here is the GFA:
```
S	1	tcatggtacttgtcaccttctgtcctatttgagtcatgatgcatttgtctatcatctatctccctgcaatgaacatccctggggtggggccagggtctgttttgcttggtgctgcattcccattgccaagaagacctcacaggcatatcaagcacacagcaggtgcataacacttgctgagtttgctgaatgaatCCCTCCTCTGTATCCTACACATCCAACTGGTCACCACGTCCTGTGCGGTAGATGTCCTTTTTAGCAGGTCCCCTGCACTTCACTGTGTTTGTTAAGCCTTGGCTTGCTCTGtcatttcattttgcttaggTGGCGGCAGCAGCCCCTGACAGCCCCTGGCCTCACAGCCCCTGGCCTCAACCCATATCCTCTCCACTCTGCACACAGCTGCTGGGAGACTTTTCCTTAAAACTtggtttctctcctttcccttctgaAAACTGTCAGTGGCTTCCTGTGGCTCAGAGGAATCAATCGAAACATGGTGCTGCTCACAAGGAAACACAACGTTTCTAGGGCCAGTGCTGTCTTTGTCCTGCCTTCCTCCAAATTCAGCCACGTTAAGCCTCAAGCAGATCCTCCCACACAGCTGGGCTTCTTCTGCCTTTCTGCCAGGACTTGCTGCTCCCAGGAGCCTCCTCCCCCAGTCCCTGCAGCCCCAGGTCAGGTGTCTCCCCACCCAGCCTGGCTCAGCTGTCCTTTCCCGTGCAACTACAGGTTCATACAATTTGCTATTGCTCCATCTACTCTATGTGACTCTTGGTTTCTTGAAGGCAGGTATGggactctttctttccttctttgctttcttttctctttctctttctttctttttctttctttctttctttctttc
S	2	tttctttctttctttctttctttctttctttctttctt
S	3	tctctctctctctctctcttttcttttctttctttctctctttctgtttttagagactgggtcttgctgtcacccaggttggagtgcagtggtgcaatcatggctcaccgaactcctgggctcaagtgagcctcttgcctcagcctcccaattagttgggactacaggcatgtgccactacacctggctaattgttattattattattattattattattatttttgtaaagacagggtcttgctctgtttcctaggctggtcttgaacccctggcctcaaatgatcctcctgcctcagcctcccaaagtgctgggattccaggagtaagataccatgtctggccTGAGAAATTTTCTAAAAGGCATGTTTTTGCACTGtccaatatgtttttctttttatcccagcctctagcacaagtgcctgactcgaacgaagcagggactctgaaatatcttgaatgaacaagtAAATGGCACTTGAATAGGTGGCCTCTAATGtgcagaggaaggaaaagggagctgacgctttccgagtgttcagtaccttctaggcaccatgctgggccttttatgtagttctcgatgaatcctcatggcatcccGCTTTGCAGAATGATTCTAGTTACCCAGAGAGCAAGTAGCCCTTAGGGTCAGGACATGCATCTGAGTTGGTCTAGTCCCAAAGCTCCTGGTCCTCTCCTGACATCActtaaacagagaaacagaactccCCTTGGGCTTCTAGGGGCGCTGGGTTCAGGAGGCACAGCCACTCCCTTTGTTCTTCCTGGCAGCTGCCCCACCAGCAGTGAGCCCATCCCacctctgggttttcttttt
L	1	+	2	+	0M
L	1	+	3	+	0M
L	2	+	3	+	0M
```

When I concatenate 1,2,3 or 1,3 and align them to the GFA, I never get an end-to-end alignment, and node 2 is always missing:
```
1       871     1       871     +       >1      871     1       871     870     870     60      tp:A:P  NM:i:0  cm:i:51 s1:i:714        s2:i:0  dv:f:0.0756     cg:Z:870=
3       841     5       836     +       >3      841     5       836     831     831     60      tp:A:P  NM:i:0  cm:i:48 s1:i:672        s2:i:0  dv:f:0.0790     cg:Z:831=
1_2_3   1750    1       857     +       >1      871     1       857     856     856     60      tp:A:P  NM:i:0  cm:i:50 s1:i:714        s2:i:0  dv:f:0.0751     cg:Z:856=
1_2_3   1750    930     1745    +       >3      841     21      836     815     815     60      tp:A:P  NM:i:0  cm:i:47 s1:i:671        s2:i:0  dv:f:0.0795     cg:Z:815=
1_3     1712    1       857     +       >1      871     1       857     856     856     60      tp:A:P  NM:i:0  cm:i:50 s1:i:700        s2:i:0  dv:f:0.0751     cg:Z:856=
1_3     1712    892     1707    +       >3      841     21      836     815     815     60      tp:A:P  NM:i:0  cm:i:47 s1:i:672        s2:i:0  dv:f:0.0795     cg:Z:815=

```

Here is a visualization showing how neither the graph nor the linear query are fully covered:
![image](https://github.com/at-cg/PanAligner/assets/28764332/801d71e6-d268-4743-a69a-35bc43230c2f)

I have tried multiple different combinations of parameters to attempt to find seeds/minimizers in node 2:

Defaults:
```
PanAligner -c -x lr -o /tmp/tmpn2oq6iyx/reads_vs_graph.gaf bad_tandem_graph.gfa bad_tandem_nodes.fasta
/tmp/tmpn2oq6iyx/reads_vs_graph.gaf
```

Permissive:
```
PanAligner -c -k 14 -n 1,1 -m 1,1 -x lr -o /tmp/tmpyid87tic/reads_vs_graph.gaf bad_tandem_graph.gfa bad_tandem_nodes.fasta
/tmp/tmpyid87tic/reads_vs_graph.gaf
```

I've also tried increasing the `-g` and `-r` parameters to allow the extension step to find more alignments, but that does not seem to have any effect. Alternatively, extreme 0/1 values of `-f` also have no effect.

Could you help me with this case? I am having difficulty understanding why the base level alignment step doesn't bridge the chains here. Ideally, I would use base level alignment for a majority of the work, and only rely on minimizers for anchoring the flanks of the tandem repeat.

Thanks

**Comment by jyotshna-atcg** [comment]
Thank you for bringing up this matter. We have conducted checks using various tools (PanAligner, [Minigraph](https://github.com/lh3/minigraph.git), and [Minichain](https://github.com/at-cg/minichain.git)), all of which produced same results. When aligning the concatenation of 1, 2, and 3, the chaining algorithm produces a chain containing anchors from nodes 1, 2, and 3. Similarly, when aligning the concatenation to 1, 3, the chaining algorithm provides a chain containing anchors from all three nodes, as the suffix of node 1 matches the label of node 2. However, during the base-to-base alignment (extension) step, node 2 is consistently discarded in the final alignment. This issue arises only when node 2 is labeled with a sequence containing tandem repeats.

The final base-to-base alignment module is borrowed from [Minigraph](https://github.com/lh3/minigraph.git), and we are actively investigating this issue. Please feel free to also raise this issue to the [Minigraph](https://github.com/lh3/minigraph.git) authors.

**Comment by rlorigro** [comment]
Hi, I have submitted a reference to this issue on the minigraph repository. 

My coworker and I have found that if you replace node 2 with random sequence there is still no end-to-end alignment. An alignment which covers node 2 exists, but the read is still broken into separate blocks.

Substituted node 2 sequence:
```
S       2       ATTTTTACTGTCACCAACCACGAGATTTGAGGTAAACCAATTGAGCACATAGTCGCGCTATCCGACAATCTCCAAATTATAACATACCGTTCCATGAAGGCCAGAGTTACTTACCGGCCCTTTCCATGCGCGCGCCATACCCCCCCAGTTCCCCGGTTATCTCTCCGAGGAGAGAGTGAGCGATCCTCCGTTAACATATTCTTACGTATGACGTAGCTATGTATTTTGCAGAGGTAGCGAACGGGTTTGACACTTCACAGATAGTGGGGATCCGGGCAAAGGGCGTATAATTGCGGTCCA
```

result:
```
1_2_3   2012    4       863     +       >1      871     4       863     859     859     60      tp:A:P  NM:i:0  cm:i:42 s1:i:714        s2:i:0  dv:f:0.0721     cg:Z:859=
1_2_3   2012    1194    2004    +       >3      841     23      833     810     810     60      tp:A:P  NM:i:0  cm:i:40 s1:i:680        s2:i:0  dv:f:0.0733     cg:Z:810=
1_2_3   2012    886     1168    +       >2      300     15      297     282     282     60      tp:A:P  NM:i:0  cm:i:14 s1:i:238        s2:i:0  dv:f:0.0674     cg:Z:282=
```

**Comment by rlorigro** [comment]
Hi @jyotshna-atcg, just wondering if there has been any progress on this? I haven't heard anything back from the minigraph authors.. maybe you have had better luck?
