### ISSUE TITLE
Segfault running PanAligner

### ISSUE THREAD

**Issue by xchang1** [at-cg/PanAligner#8]
Hello,

I am trying to run PanAligner on this [hprc graph](https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/freeze1/minigraph-cactus/hprc-v1.1-mc-chm13/hprc-v1.1-mc-chm13.d9.gbz) and it fails with a segfault and no error message.
Do you have any advice on getting it to run or how to figure out what the problem is?

This is the command I ran:
```
PanAligner -cx lr -t 12 graph.gfa.gz badread.fa > mapped.panaligner.gaf
```
The graph is the hprc v1.1 minigraph-cactus chm13 d9 frequency filtered graph, which I converted to a gfa with `vg convert`.
I've run other mappers with the same gfa so I don't think that's the problem, unless PanAligner requires something specific that I missed.
The read I ran is a simulated hifi read, but it has segfaulted on everything I've tried.

Thanks!
Xian

**Comment by cjain7** [comment]
Hello,
AFAIK, Unfortunately PanAligner is not engineered to handle graphs with SNPs and indels. It only works with graphs built using [Minigraph](https://github.com/lh3/minigraph). Minigraph graphs will be much simpler because these only include SVs.

cc @jyotshna-atcg @gsc74

**Comment by xchang1** [comment]
Ah ok, I didn't realize. Thanks!
